import hub
import utime
import ujson 

# Constant Definitions
TIMEOUT = 1000

#for some reason the connected boolean is return as false
def connected(btconnect):
    if btconnect.isconnected():
        print("Currently connected via bluetooth")
    else:
        print("Not connected rn")
def printLog(msg):
    print("************Message log************\n " + msg + "\n************End of log************")

#Start of main program, Happy Halloween 2021
hub.display.show(hub.Image.GHOST)
utime.sleep(2)

#Object to read and write over bluetooth
bt = hub.BT_VCP(0)

#If the bt object was successfully created, there should be a open connection
if bt:
    # Now we read in the input file (as generated by INPUT_FILE_NAME.py (our Quorum -> JSON file))
    # The contents of the input file to function properly with the following code should be
    # JSON objects separated by newlines representing individual commands to be run on the hub
    # Create a list of lines from the program
    contents = []
    with open('anyfile.txt') as file:
        contents = [line.strip() for line in file]

    # Now that we have them split, prep them to send 
    for line in contents:
        command = ujson.dumps(line)
        bt.send(command,TIMEOUT) 

#Unsuccesful connection
else:
    print("FALSE")
    hub.display.show(hub.Image.SAD)